### ISSUE TITLE
`working_dir` doesn't work

### ISSUE THREAD

**Issue by MrFoxPro** [Platonic-Systems/process-compose-flake#25]
```nix
process-compose.dev = {
  tui = false;
  settings = {
    processes = {
      web = {
        command = "echo $PWD";
        working_dir = with {p = toString ./api;}; builtins.trace p p;
      };
    };
  };
};
```
I guess process-compose can't access source directory because of permissions restrictions.

**Comment by MrFoxPro** [comment]
Hm, it's working when running from package, but not from shell:
```nix
web = {
  command = pkgs.nuenv.mkSimpleScript "cmd.nu" "print 'HI'; print $env.PWD ";
  working_dir = "/home/foxpro/craft/sferadel/next/api";
};
```

```
processes:
  web:
    command: /nix/store/26y922y4rdvf8hhwarqi7n50izmndjbz-cmd.nu/bin/cmd.nu
    working_dir: /home/foxpro/craft/sferadel/next/api
shell:
  shell_argument: -c
  shell_command: /nix/store/mh1c3p23xby3chc3q0c0g78fa1nn65yw-bash-5.2-p15/bin/bash
[web_1  ] HI
[web_1  ] /home/foxpro/craft/sferadel/next/api
```
